depot/urls.py
from django.urls import path
from .views.depot_create_rental_view import DepotCreateRentalView
from .views.depot_detail_view import DepotDetailView
from .views.depot_index_view import DepotIndexView
from .views.depot_rentals_view import DepotRentalsView

app_name = 'depot'
urlpatterns = [
    path('', DepotIndexView.as_view(), name='index'),
    path('<int:depot_id>/', DepotDetailView.as_view(), name='detail'),
    path('<int:depot_id>/rentals/', DepotRentalsView.as_view(), name='rentals'),
    path('<int:depot_id>/rentals/create/', DepotCreateRentalView.as_view(),
         name='create_rental')
]

login/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

verleihtool/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path('', include('login.urls')),
    path('depots/', include('depot.urls')),
    path('rentals/', include('rental.urls')),
    path('admin/', admin.site.urls),
    prefix_default_language=False
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Remove the above line in production and serve the static files properly
# https://docs.djangoproject.com/en/dev/howto/static-files/

verleihtool/templates/layout.html
{% load static %}
{% load i18n %}
{% load tags %}

{% get_current_language as lang_code %}

<!DOCTYPE html>
<html lang="{{ lang_code }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% get_available_languages as languages %}
        {% for lang, name in languages %}
            <link rel="alternate" href="{% change_lang lang %}" hreflang="{{ lang }}" type="text/html">
        {% endfor %}

        <title>
            {% block title %}{% trans 'Welcome' %}{% endblock %} - Verleihtool
        </title>
        <link href="{% static 'app.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed"
                                data-toggle="collapse" data-target="#navbar"
                                aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">{% trans 'Toggle navigation' %}</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'login:home' %}">
                            Verleihtool
                        </a>
                    </div>
                    <div id="navbar" class="collapse navbar-collapse">
                        <!-- Left Side Of Navbar -->
                        <ul class="nav navbar-nav">
                            <li class="{% current_app 'login' 'active' %}">
                                <a href="{% url 'login:home' %}">{% trans 'Home' %}</a>
                            </li>
                            <li class="{% current_app 'depot' 'active' %}">
                                <a href="{% url 'depot:index' %}">{% trans 'Depots' %}</a>
                            </li>
                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle"
                                            data-toggle="dropdown" role="button"
                                            aria-haspopup="true" aria-expanded="false">
                                        {{ user|full_name }} <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        {% if user.is_superuser %}
                                            <li>
                                                <a href="{% url 'admin:index' %}" target="_blank">
                                                    {% trans 'Administration' %}
                                                </a>
                                            </li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url 'login:logout' %}">
                                                {% trans 'Logout' %}
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            {% else %}
                                <li class="dropdown" id="login-dropdown">
                                    <a href="{% url 'login:login' %}" class="dropdown-toggle"
                                            data-toggle="dropdown" role="button"
                                            aria-haspopup="true" aria-expanded="false">
                                        {% trans 'Login' %} <span class="caret"></span>
                                    </a>
                                    <div class="dropdown-menu login-form" role="menu">
                                        {% include 'login/login-form.html' %}
                                    </div>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% block container %}
                <div class="container">
                    {% block content %}
                    {% endblock %}
                </div>
            {% endblock %}

            <footer class="footer">
                <div class="container">
                    <div class="btn-group dropup pull-right language-picker">
                        <button type="button" class="btn btn-default dropdown-toggle" id="change-language"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                            {% trans 'Change language' %}
                            <span class="caret"></span>
                        </button>

                        <ul class="dropdown-menu" aria-labelledby="change-language">
                            {% get_available_languages as languages %}
                            {% for lang, name in languages %}
                                <li>
                                    <a href="{% change_lang lang %}">
                                        {% language lang %}
                                            {% get_language_info for lang as lang_info %}
                                            {{ lang_info.name_local }} ({{ lang }})
                                        {% endlanguage %}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <p class="text-muted link-list">
                        <a href="{{ PRIVACY_URL }}">{% trans 'Privacy' %}</a>
                        <a href="{{ IMPRINT_URL }}">{% trans 'Imprint' %}</a>
                        <a href="{{ GITHUB_URL }}">{% trans 'Github' %}</a>
                    </p>
                </div>
            </footer>
        </div>

        <script src="{% static 'app.js' %}"></script>
    </body>
</html>