depot/urls.py
from django.urls import path
from .views.depot_create_rental_view import DepotCreateRentalView
from .views.depot_detail_view import DepotDetailView
from .views.depot_index_view import DepotIndexView
from .views.depot_rentals_view import DepotRentalsView

app_name = 'depot'
urlpatterns = [
    path('', DepotIndexView.as_view(), name='index'),
    path('<int:depot_id>/', DepotDetailView.as_view(), name='detail'),
    path('<int:depot_id>/rentals/', DepotRentalsView.as_view(), name='rentals'),
    path('<int:depot_id>/rentals/create/', DepotCreateRentalView.as_view(),
         name='create_rental')
]

rental/urls.py
from django.urls import path
from .views.rental_create_view import RentalCreateView
from .views.rental_detail_view import RentalDetailView
from .views.rental_state_view import RentalStateView

app_name = 'rental'
urlpatterns = [
    path('create/', RentalCreateView.as_view(), name='create'),
    path('<uuid:rental_uuid>/', RentalDetailView.as_view(), name='detail'),
    path('<uuid:rental_uuid>/state/', RentalStateView.as_view(), name='state'),
]

verleihtool/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path('', include('login.urls')),
    path('depots/', include('depot.urls')),
    path('rentals/', include('rental.urls')),
    path('admin/', admin.site.urls),
    prefix_default_language=False
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Remove the above line in production and serve the static files properly
# https://docs.djangoproject.com/en/dev/howto/static-files/

rental/models.py
import uuid
from datetime import datetime
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from depot.models import Depot, Item


class Rental(models.Model):
    """
    A rental defines the amount of items and has a start and return date.
    Only items from one depot can be requested for rental at once.

    When requesting a rental, the user has to enter his full name and email
    address as well as describing the purpose of his rental. If they are
    logged in, the user's id will be stored as well.

    After creating a rental request, it is in the PENDING state. From this,
    it can be either APPROVED or DECLINED by a depot manager or REVOKED by
    the requesting user. If all items were returned correctly, it can be
    set to RETURNED to finish the rental process.

    :author: Benedikt Seidl
    """

    STATE_PENDING = '1'
    STATE_APPROVED = '2'
    STATE_DECLINED = '3'
    STATE_REVOKED = '4'
    STATE_RETURNED = '5'
    STATES = (
        (STATE_PENDING, _('pending')),
        (STATE_APPROVED, _('approved')),
        (STATE_DECLINED, _('declined')),
        (STATE_REVOKED, _('revoked')),
        (STATE_RETURNED, _('returned')),
    )

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    depot = models.ForeignKey(Depot, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, through='ItemRental')
    firstname = models.CharField(max_length=32)
    lastname = models.CharField(max_length=32)
    email = models.EmailField()
    purpose = models.CharField(max_length=256)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    start_date = models.DateTimeField()
    return_date = models.DateTimeField()
    state = models.CharField(max_length=1, choices=STATES, default=STATE_PENDING)

    def clean(self):
        if not self.depot.active:
            raise ValidationError({'depot': 'The depot has to be active.'})

        if self.start_date > self.return_date:
            raise ValidationError({
                'start_date': 'The start date must be before the return date.'
            })

        if self.start_date < datetime.now() and self.state == self.STATE_PENDING:
            raise ValidationError({
                'start_date': 'The start date must be in the future for new rentals.'
            })

    def __str__(self):
        return 'Rental by %s %s' % (self.firstname, self.lastname)


class ItemRental(models.Model):
    """
    Intermediate relationship for each item within a rental.
    Defines the quantity and number of returned items.

    :author: Benedikt Seidl
    """

    rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    returned = models.PositiveSmallIntegerField(default=0)

    def clean(self):
        if self.rental.depot_id != self.item.depot_id:
            raise ValidationError({
                'item': 'The item must come from the depot the rental was created for.'
            })

        if self.item.visibility != Item.VISIBILITY_PUBLIC:
            organization = self.rental.depot.organization
            user = self.rental.user

            if user is None or not organization.is_member(user):
                raise ValidationError({
                    'item': 'You have to be a member of the organization '
                            'that manages this depot to rent an internal item.'
                })

        if self.quantity <= 0 or self.quantity > self.item.quantity:
            raise ValidationError({
                'quantity': 'The quantity must be positive and less than or '
                            'equal to the total amount of available items.'
            })

        if self.returned > self.quantity:
            raise ValidationError({
                'returned': 'The amount of returned items must be less than or '
                            'equal to the total amount of rented items.'
            })

depot/views/depot_create_rental_view.py
from datetime import datetime, timedelta
from depot.helpers import get_depot_if_allowed, extract_item_quantities
from django.shortcuts import render
from django.views import View
from rental.availability import Availability


class DepotCreateRentalView(View):
    """
    Show a form to create a new rental for the given depot

    :author: Benedikt Seidl
    """

    def get(self, request, depot_id):
        depot = get_depot_if_allowed(depot_id, request.user)

        # configure time frame
        start_date, return_date = self.get_start_return_date(request.GET)

        item_list = depot.visible_items(request.user)

        availability = Availability(
            datetime.combine(start_date.date() - timedelta(days=1), datetime.min.time()),
            datetime.combine(return_date.date() + timedelta(days=1), datetime.min.time()),
            depot_id
        )

        availability_data = []

        for item in item_list:
            intervals = availability.get_availability_intervals(item)

            availability_data.append((
                item,
                self.get_chart_data(intervals),
                min(intervals).value
            ))

        errors = request.session.pop('errors', None)
        data = request.session.pop('data', {})

        return render(request, 'depot/create-rental.html', {
            'depot': depot,
            'show_visibility': depot.show_internal_items(request.user),
            'availability_data': availability_data,
            'errors': errors,
            'data': data,
            'item_quantities': extract_item_quantities(data),
            'start_date': start_date,
            'return_date': return_date,
            'start_date_formatted': start_date.strftime('%Y-%m-%d %H:%M'),
            'return_date_formatted': return_date.strftime('%Y-%m-%d %H:%M')
        })

    def get_start_return_date(self, data):
        """
        Return the start and return dates from the request

        If required data is missing or invalid, default values are returned.
        """

        try:
            start_date = datetime.strptime(data.get('start_date'), '%Y-%m-%d %H:%M')
        except (ValueError, TypeError):
            start_date = datetime.now() + timedelta(days=1)

        try:
            return_date = datetime.strptime(data.get('return_date'), '%Y-%m-%d %H:%M')
        except (ValueError, TypeError):
            return_date = start_date + timedelta(days=3)

        return (start_date, max(start_date, return_date))

    def get_chart_data(self, intervals):
        """
        Generate the data the JavaScript can render
        """

        data = []

        for interval in intervals:
            data.append({
                "x": interval.begin.isoformat(),
                "y": interval.value
            })
            data.append({
                "x": interval.end.isoformat(),
                "y": interval.value
            })

        return data

depot/views/depot_detail_view.py
from datetime import datetime, timedelta
from depot.helpers import get_depot_if_allowed
from django.shortcuts import render
from django.views import View


class DepotDetailView(View):
    """
    Provide a detailed overview of all items in a depot

    Archived depots can only be accessed by superusers and organization managers.
    The internal items of a depot can be seen by all members of this organization.

    :author: Florian Stamer
    """

    def get(self, request, depot_id):
        depot = get_depot_if_allowed(depot_id, request.user)
        item_list = depot.visible_items(request.user)

        return render(request, 'depot/detail.html', {
            'depot': depot,
            'item_list': item_list,
            'show_visibility': depot.show_internal_items(request.user),
            'managed_by_user': depot.managed_by(request.user),
            'start_date': datetime.now() + timedelta(days=1),
            'return_date': datetime.now() + timedelta(days=4)
        })

depot/views/depot_index_view.py
from django.shortcuts import render
from django.views import View
from depot.models import Organization


class DepotIndexView(View):
    """
    Show an index page of all organizations and their depots

    Only organization managers get a link to the admin interface of their
    organization so that they can change the name and add new depots.

    :author: Florian Stamer
    :author: Benedikt Seidl
    """

    def get(self, request):
        organization_depots = []

        for organization in Organization.objects.all():
            managed_by_user = organization.managed_by(request.user)
            depots = organization.active_depots.all()

            if depots:
                organization_depots.append({
                    'model': organization,
                    'managed_by_user': managed_by_user,
                    'depots': depots
                })

        return render(request, 'depot/index.html', {
            'organization_depots': organization_depots
        })

depot/views/depot_rentals_view.py
from depot.models import Depot
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.views import View
from rental.models import Rental


class DepotRentalsView(View):
    """
    Provide an overview over all rentals for one depot

    Show labels to visually differentiate the state a
    rental is in.

    :author: Florian Stamer
    """

    def get(self, request, depot_id):
        depot = get_object_or_404(Depot, pk=depot_id)

        if not depot.managed_by(request.user):
            return HttpResponseForbidden('Not a manager of this depot')

        rentals = Rental.objects.filter(
            depot_id=depot.id,
            state__in=[Rental.STATE_PENDING, Rental.STATE_APPROVED]
        )

        return render(request, 'depot/rentals.html', {
            'rentals': rentals,
            'depot': depot,
        })

rental/views/rental_create_view.py
import markdown
import urllib
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views import View
from depot.helpers import extract_item_quantities
from depot.models import Item
from rental.availability import Availability
from rental.models import Rental, ItemRental


class RentalCreateView(View):
    """
    Create a new rental object and assign the selected items to it

    When the object is successfully created, the user is redirected
    to the detail view of the new rental.
    If an error occurs, the message dictionary is stored in the
    current session and the user gets back to the edit view to
    correct their mistakes.

    :author: Florian Stamer
    """

    def post(self, request):
        data = request.POST

        user = request.user if request.user.is_authenticated else None

        try:
            # The transaction is cancelled if an unhandled exception occurs
            # in the following block
            with transaction.atomic():
                rental = self.create_rental(user, data)
                self.create_items(rental, data)

            # After transaction send a confirmation mail to the user
            self.send_confirmation_mail(request, rental)

            # Finally redirect the user to the rental page
            return redirect('rental:detail', rental_uuid=rental.uuid)
        except ValidationError as e:
            # Store the errors and the submitted data in the current session
            request.session['errors'] = e.message_dict
            request.session['data'] = data

            # Redirect to the form where the errors are displayed
            response = redirect('depot:create_rental', depot_id=data.get('depot_id'))
            response['Location'] += '?' + urllib.parse.urlencode({
                'start_date': data.get('start_date'),
                'return_date': data.get('return_date')
            })

            return response

    def create_rental(self, user, data):
        keys = (
            'firstname', 'lastname', 'depot_id', 'email', 'purpose', 'start_date', 'return_date'
        )
        rental = Rental(user=user, **{key: data.get(key) for key in keys})
        rental.full_clean()
        rental.save()
        # Refresh Rental object to fix issue with depot_id
        rental.refresh_from_db()
        return rental

    def create_items(self, rental, data):
        errors = {}

        item_quantities = extract_item_quantities(data)

        if not item_quantities:
            raise ValidationError({
                'item_quantities': 'The rental cannot be submitted without any items.'
            })

        item_list = Item.objects.filter(id__in=item_quantities.keys())

        availability = Availability(rental.start_date, rental.return_date, rental.depot_id)

        for item in item_list:
            intervals = availability.get_availability_intervals(item)

            try:
                available = min(intervals).value
                self.create_item_rental(rental, item, item_quantities[item.id], available)
            except ValidationError as e:
                for key, value in e:
                    errors['%s %s' % (item.name, key)] = value

        if errors:
            raise ValidationError(errors)

    def create_item_rental(self, rental, item, quantity, available):
        if quantity > available:
            raise ValidationError({
                'quantity': 'The quantity must not exceed the availability '
                            'of the item in the requested time frame.'
            })

        item_rental = ItemRental(
            rental=rental,
            item=item,
            quantity=quantity
        )
        item_rental.full_clean()
        item_rental.save()

    def send_confirmation_mail(self, request, rental):
        subject = ('[Verleihtool] Your rental request, %s %s' %
                   (rental.firstname, rental.lastname))
        message = render_to_string('rental/mails/confirmation.md', {
            'rental': rental
        }, request)

        email = EmailMultiAlternatives(
            subject=subject,
            body=message,
            to=[rental.email],
            cc=settings.CC_EMAIL,
        )

        email.attach_alternative(markdown.markdown(message), 'text/html')

        email.send()

rental/views/rental_detail_view.py
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _
from django.views import View
from rental.models import Rental
from rental.state_transitions import allowed_transitions


class RentalDetailView(View):
    """
    Provide necessary information for a rentals detail page

    This includes buttons to change the rentals state,
    an alert with information about the rentals state
    and a list of rented items.

    :author: Florian Stamer
    """

    def get(self, request, rental_uuid):
        rental = get_object_or_404(Rental, pk=rental_uuid)
        managed_by_user = rental.depot.managed_by(request.user)

        states = allowed_transitions(managed_by_user, rental.state)

        btn_texts = {
            Rental.STATE_PENDING: _('Reset'),
            Rental.STATE_REVOKED: _('Revoke'),
            Rental.STATE_APPROVED: _('Approve'),
            Rental.STATE_DECLINED: _('Decline'),
            Rental.STATE_RETURNED: _('Finish'),
        }

        return render(request, 'rental/detail.html', {
            'rental': rental,
            'managed_by_user': managed_by_user,
            'states': states,
            'btn_texts': btn_texts,
        })

depot/templates/depot/create-rental.html
{% extends 'layout.html' %}

{% load tags %}
{% load i18n %}

{% block title %}
    {% blocktrans trimmed with depot_name=depot.name %}
        New Rental for {{ depot_name }}
    {% endblocktrans %}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'depot:index' %}">{% trans 'Depots' %}</a>
        </li>
        <li>
            <a href="{% url 'depot:detail' depot.id %}">{{ depot.name }}</a>
        </li>
        <li class="active">
            <span>{% trans 'New Rental' %}</span>
        </li>
    </ol>

    {% if errors %}
        <div class="alert alert-danger" role="alert">
            {% trans 'Please fix the errors below and in the checkout form.' %}

            <a href="#errors-collapse" class="alert-link pull-right" data-toggle="collapse">
                <span class="caret"></span>
            </a>

            <div class="collapse" id="errors-collapse">
                <hr>
                <dl class="dl-horizontal">
                    {% for key, error_list in errors.items %}
                        <dt>{{ key }}</dt>
                        <dd>
                            {% for error in error_list %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </dd>
                    {% endfor %}
                </dl>
            </div>
        </div>
    {% endif %}

    <div class="page-header">
        <h1>
            {% blocktrans trimmed with depot_name=depot.name %}
                New Rental <small>for {{ depot_name }}</small>
            {% endblocktrans %}
        </h1>
    </div>

    <p>
        {% trans 'Create a new rental' %}
        <a href="#date-modal" data-toggle="modal">
            {% blocktrans trimmed %}
                from {{ start_date }} to {{ return_date }}.
            {% endblocktrans %}
        </a>
    </p>

    <div class="panel panel-default">
        <div class="panel-body">
            {% blocktrans trimmed %}
                Hint: You can click on the number of available items
                to get a detailed view of its availability over time.
            {% endblocktrans %}
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans 'Name' %}</th>
                        <th class="text-center">{% trans 'Available' %}</th>
                        <th>{% trans 'Location' %}</th>
                        {% if show_visibility %}
                            <th class="text-center">{% trans 'Visibility' %}</th>
                        {% endif %}
                        <th>{% trans 'Selected' %}</th>
                    </tr>
                </thead>

                <tbody>
                    {% for item, intervals, availability in availability_data %}
                        <tr class="rental-item">
                            <th scope="row">
                                {{ forloop.counter }}
                            </th>
                            <td class="rental-item-name">
                                {{ item.name }}
                            </td>
                            <td class="rental-item-availability text-center">
                                <a class="badge"
                                        data-toggle="modal"
                                        data-target="#availability-modal"
                                        data-name="{{ item.name }}"
                                        data-intervals="{{ intervals|tojson }}">
                                    {{ availability }}
                                </a>
                            </td>
                            <td class="rental-item-location">
                                {{ item.location }}
                            </td>
                            {% if show_visibility %}
                                <td class="text-center">
                                    <span class="glyphicon glyphicon-{% item_visibility_glyphicon item.visibility %}"
                                            aria-hidden="true"
                                            data-toggle="tooltip"
                                            data-placement="right"
                                            title="{% item_visibility item.visibility %}">
                                    </span>
                                    <span class="sr-only">{% item_visibility item.visibility %}</span>
                                </td>
                            {% endif %}
                            <td class="rental-item-selected">
                                <div class="input-group number-input">
                                    <input type="text" class="form-control"
                                            value="{% firstof item_quantities|key:item.id '0' %}"
                                            data-name="item-{{ item.id }}-quantity"
                                            data-min="0" data-max="{{ availability }}">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-default number-input-up">
                                            <span class="glyphicon glyphicon-chevron-up"></span>
                                        </button>
                                        <button type="button" class="btn btn-default number-input-down">
                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <button type="button" class="btn btn-primary" id="checkout-button"
                    data-toggle="modal" data-target="#checkout-modal"
                    {% if not errors %} disabled {% endif %}>
                {% trans 'Checkout' %}
            </button>

            <button type="button" class="btn btn-default"
                    data-toggle="modal" data-target="#date-modal">
                {% trans 'Change time frame' %}
            </button>
        </div>
    </div>

    {% include 'depot/modals/checkout-modal.html' %}
    {% include 'depot/modals/date-modal.html' %}
    {% include 'depot/modals/availability-modal.html' %}
{% endblock %}

depot/templates/depot/detail.html
{% extends 'layout.html' %}

{% load tags %}
{% load i18n %}

{% block title %}
    {% blocktrans trimmed with depot_name=depot.name organization_name=depot.organization.name %}
        {{ depot_name }} by {{ organization_name }}
    {% endblocktrans %}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'depot:index' %}">{% trans 'Depots' %}</a>
        </li>
        <li class="active">
            <span>{{ depot.name }}</span>
        </li>
    </ol>

    <div class="page-header">
        <h1>
            {% blocktrans trimmed with depot_name=depot.name organization_name=depot.organization.name %}
                {{ depot_name }} <small>by {{ organization_name }}</small>
            {% endblocktrans %}

            {% if managed_by_user %}
                <a href="{% url 'admin:depot_depot_change' depot.id %}"
                        class="btn btn-default" target="_blank">
                    {% trans 'Manage' %}
                </a>
                <a href="{% url 'depot:rentals' depot.id %}"
                        class="btn btn-default">
                    {% trans 'Rentals' %}
                </a>
            {% endif %}
        </h1>
    </div>

    <p>
        {% concat_with_and depot.managers|full_names empty=_('no one apparently') as managers %}
        {% blocktrans trimmed %}
            This depot is managed by {{ managers }}.
        {% endblocktrans %}
    </p>

    <div class="panel panel-default">
        <div class="panel-body">
            {% if depot.description %}
                {{ depot.description }}
            {% else %}
                <i>{% trans 'No description provided' %}</i>
            {% endif %}
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Description' %}</th>
                        <th class="text-center">{% trans 'Quantity' %}</th>
                        <th>{% trans 'Location' %}</th>
                        {% if show_visibility %}
                            <th class="text-center">{% trans 'Visibility' %}</th>
                        {% endif %}
                    </tr>
                </thead>

                <tbody>
                    {% for item in item_list %}
                        <tr>
                            <th scope="row">
                                {{ forloop.counter }}
                            </th>
                            <td>
                                {{ item.name }}
                            </td>
                            <td>
                                {{ item.description }}
                            </td>
                            <td class="text-center">
                                <span class="badge">{{ item.quantity }}</span>
                            </td>
                            <td>
                                {{ item.location }}
                            </td>
                            {% if show_visibility %}
                                <td class="text-center">
                                    <span class="glyphicon glyphicon-{% item_visibility_glyphicon item.visibility %}"
                                            aria-hidden="true"
                                            data-toggle="tooltip"
                                            data-placement="right"
                                            title="{% item_visibility item.visibility %}">
                                    </span>
                                    <span class="sr-only">{% item_visibility item.visibility %}</span>
                                </td>
                            {% endif %}
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="text-center" colspan="99">
                                <i>{% trans 'No items available' %}</i>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <button type="button" class="btn btn-primary"
                    data-toggle="modal" data-target="#date-modal"
                    {% if not item_list %} disabled {% endif %}>
                {% trans 'Request rental' %}
            </button>
        </div>
    </div>

    {% include 'depot/modals/date-modal.html' %}
{% endblock %}

depot/templates/depot/rentals.html
{% extends 'layout.html' %}

{% load tags %}
{% load i18n %}

{% block title %}
    {% trans 'Rentals' %}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'depot:index' %}">{% trans 'Depots' %}</a>
        </li>
        <li>
            <a href="{% url 'depot:detail' depot.id %}">{{ depot.name }}</a>
        </li>
        <li class="active">
            <span>{% trans 'Rentals' %}</span>
        </li>
    </ol>

    <div class="page-header">
        <h1>
            {% blocktrans trimmed with depot_name=depot.name %}
                Rentals <small>for {{ depot_name }}</small>
            {% endblocktrans %}

            <a href="{% url 'admin:rental_rental_changelist' %}?depot__id__exact={{ depot.id }}"
                    class="btn btn-default" target="_blank">
                {% trans 'Manage' %}
            </a>
        </h1>
    </div>

    <div class="panel panel-default">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Number of items' %}</th>
                        <th>{% trans 'Start date' %}</th>
                        <th>{% trans 'Return date' %}</th>
                        <th>{% trans 'State' %}</th>
                    </tr>
                </thead>

                <tbody>
                    {% for rental in rentals %}
                        <tr class="clickable-area">
                            <th scope="row">
                                <a class="clickable-area-link"
                                    href="{% url 'rental:detail' rental.uuid %}"
                                    aria-hidden="true">
                                </a>
                                {{ forloop.counter }}
                            </th>
                            <td>{{ rental.firstname }} {{ rental.lastname }}</td>
                            <td>{{ rental.itemrental_set.all.count }}
                            <td>{{ rental.start_date }}</td>
                            <td>{{ rental.return_date }}</td>
                            <td>
                                <span class="label label-{% rental_state_class rental.state %}">
                                    {% rental_state rental.state %}
                                </span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="text-center" colspan="99">
                                <i>{% trans 'No open requests at the moment' %}</i>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}