depot/urls.py
from django.urls import path
from .views.depot_create_rental_view import DepotCreateRentalView
from .views.depot_detail_view import DepotDetailView
from .views.depot_index_view import DepotIndexView
from .views.depot_rentals_view import DepotRentalsView

app_name = 'depot'
urlpatterns = [
    path('', DepotIndexView.as_view(), name='index'),
    path('<int:depot_id>/', DepotDetailView.as_view(), name='detail'),
    path('<int:depot_id>/rentals/', DepotRentalsView.as_view(), name='rentals'),
    path('<int:depot_id>/rentals/create/', DepotCreateRentalView.as_view(),
         name='create_rental')
]

rental/urls.py
from django.urls import path
from .views.rental_create_view import RentalCreateView
from .views.rental_detail_view import RentalDetailView
from .views.rental_state_view import RentalStateView

app_name = 'rental'
urlpatterns = [
    path('create/', RentalCreateView.as_view(), name='create'),
    path('<uuid:rental_uuid>/', RentalDetailView.as_view(), name='detail'),
    path('<uuid:rental_uuid>/state/', RentalStateView.as_view(), name='state'),
]

verleihtool/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path('', include('login.urls')),
    path('depots/', include('depot.urls')),
    path('rentals/', include('rental.urls')),
    path('admin/', admin.site.urls),
    prefix_default_language=False
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Remove the above line in production and serve the static files properly
# https://docs.djangoproject.com/en/dev/howto/static-files/

depot/models.py
from django.contrib.auth.models import Group, User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Organization(models.Model):
    """
    Representation of an organization,
    such as FSMPI, FSMB or ASTA.

    An organization is defined by a list of user groups,
    in our case LDAP groups. It is managed by a list of
    users and has a list of depots.

    :author: Leo Tappe
    :author: Benedikt Seidl
    """

    name = models.CharField(max_length=32)
    groups = models.ManyToManyField(Group, blank=True)
    managers = models.ManyToManyField(User, blank=True)

    def managed_by(self, user):
        """
        Organizations are managed by superusers and organization managers.
        """

        return user.is_superuser or self.managers.filter(id=user.id).exists()

    def is_member(self, user):
        """
        Checks if the user is in one of the groups defined in this organization.
        """

        return self.groups.filter(id__in=user.groups.all()).exists()

    @property
    def active_depots(self):
        """
        Returns all depots in this organization which have the active flag set.
        """

        return self.depot_set.filter(active=True)

    @staticmethod
    def filter_by_user(user):
        """
        Filter for organizations managed by the given user
        """

        return models.Q(managers__id=user.id)

    def __str__(self):
        return self.name


class Depot(models.Model):
    """
    A depot has a name and many depot managers.

    :author: Leo Tappe
    :author: Benedikt Seidl
    """

    name = models.CharField(max_length=32)
    description = models.CharField(max_length=256, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    manager_users = models.ManyToManyField(User, blank=True)
    manager_groups = models.ManyToManyField(Group, blank=True)
    active = models.BooleanField(default=True)

    def managed_by(self, user):
        """
        Depots are managed by superusers, the organization's managers,
        any manager user and any user in a manager group.
        """

        return (user.is_superuser
                or self.organization.managed_by(user)
                or self.manager_users.filter(id=user.id).exists()
                or self.manager_groups.filter(id__in=user.groups.all()).exists())

    def show_internal_items(self, user):
        """
        Internal items can be seen by superusers and organization members.
        """

        return user.is_superuser or self.organization.is_member(user)

    def visible_items(self, user):
        """
        Return the list of items the user is allowed to see in this depot.
        """

        if self.show_internal_items(user):
            return self.active_items.all()
        else:
            return self.public_items.all()

    @property
    def managers(self):
        """
        The list of users explicitly listed as managers of this depot.
        Does not include any organization managers or superusers which are
        not added to the depot.
        """

        return User.objects.filter(
            models.Q(id__in=self.manager_users.all())
            | models.Q(groups__in=self.manager_groups.all())
        ).distinct()

    @property
    def public_items(self):
        """
        List all items with the visibility set to public.
        """

        return self.item_set.filter(visibility=Item.VISIBILITY_PUBLIC)

    @property
    def active_items(self):
        return self.item_set.filter(
            models.Q(visibility=Item.VISIBILITY_PUBLIC)
            | models.Q(visibility=Item.VISIBILITY_INTERNAL)
        )

    @staticmethod
    def filter_by_user(user):
        """
        Filter for depots managed by the given user
        """

        return (models.Q(organization__managers__id=user.id)
                | models.Q(manager_users__id=user.id)
                | models.Q(manager_groups__id__in=user.groups.all()))

    def __str__(self):
        return self.name


class Item(models.Model):
    """
    An item describes one or more instances of an object in a depot.

    It always belongs to a single depot and has a unique name within the depot.
    The location field can be used to roughly describe where
    the item can be found in the depot.
    Items can either be public or internal which affects the visibility
    of the item to users outside of the organization connected to the depot.
    The quantity describes how many version of the item exist in the depot.

    :author: Leo Tappe
    """

    VISIBILITY_PUBLIC = '1'
    VISIBILITY_INTERNAL = '2'
    VISIBILITY_DELETED = '3'
    VISIBILITY_LEVELS = (
        (VISIBILITY_PUBLIC, _('public')),
        (VISIBILITY_INTERNAL, _('internal')),
        (VISIBILITY_DELETED, _('deleted')),
    )

    name = models.CharField(max_length=32)
    description = models.CharField(max_length=1024, blank=True)
    quantity = models.PositiveSmallIntegerField()
    visibility = models.CharField(max_length=1, choices=VISIBILITY_LEVELS)
    location = models.CharField(max_length=256, blank=True)
    depot = models.ForeignKey(Depot, on_delete=models.CASCADE)

    @staticmethod
    def filter_by_user(user):
        """
        Filter for items managed by the given user
        """

        return (models.Q(depot__organization__managers__id=user.id)
                | models.Q(depot__manager_users__id=user.id)
                | models.Q(depot__manager_groups__id__in=user.groups.all()))

    class Meta:
        unique_together = (
            ('name', 'depot'),
        )

    def __str__(self):
        return self.name

depot/views/depot_create_rental_view.py
from datetime import datetime, timedelta
from depot.helpers import get_depot_if_allowed, extract_item_quantities
from django.shortcuts import render
from django.views import View
from rental.availability import Availability


class DepotCreateRentalView(View):
    """
    Show a form to create a new rental for the given depot

    :author: Benedikt Seidl
    """

    def get(self, request, depot_id):
        depot = get_depot_if_allowed(depot_id, request.user)

        # configure time frame
        start_date, return_date = self.get_start_return_date(request.GET)

        item_list = depot.visible_items(request.user)

        availability = Availability(
            datetime.combine(start_date.date() - timedelta(days=1), datetime.min.time()),
            datetime.combine(return_date.date() + timedelta(days=1), datetime.min.time()),
            depot_id
        )

        availability_data = []

        for item in item_list:
            intervals = availability.get_availability_intervals(item)

            availability_data.append((
                item,
                self.get_chart_data(intervals),
                min(intervals).value
            ))

        errors = request.session.pop('errors', None)
        data = request.session.pop('data', {})

        return render(request, 'depot/create-rental.html', {
            'depot': depot,
            'show_visibility': depot.show_internal_items(request.user),
            'availability_data': availability_data,
            'errors': errors,
            'data': data,
            'item_quantities': extract_item_quantities(data),
            'start_date': start_date,
            'return_date': return_date,
            'start_date_formatted': start_date.strftime('%Y-%m-%d %H:%M'),
            'return_date_formatted': return_date.strftime('%Y-%m-%d %H:%M')
        })

    def get_start_return_date(self, data):
        """
        Return the start and return dates from the request

        If required data is missing or invalid, default values are returned.
        """

        try:
            start_date = datetime.strptime(data.get('start_date'), '%Y-%m-%d %H:%M')
        except (ValueError, TypeError):
            start_date = datetime.now() + timedelta(days=1)

        try:
            return_date = datetime.strptime(data.get('return_date'), '%Y-%m-%d %H:%M')
        except (ValueError, TypeError):
            return_date = start_date + timedelta(days=3)

        return (start_date, max(start_date, return_date))

    def get_chart_data(self, intervals):
        """
        Generate the data the JavaScript can render
        """

        data = []

        for interval in intervals:
            data.append({
                "x": interval.begin.isoformat(),
                "y": interval.value
            })
            data.append({
                "x": interval.end.isoformat(),
                "y": interval.value
            })

        return data

depot/views/depot_detail_view.py
from datetime import datetime, timedelta
from depot.helpers import get_depot_if_allowed
from django.shortcuts import render
from django.views import View


class DepotDetailView(View):
    """
    Provide a detailed overview of all items in a depot

    Archived depots can only be accessed by superusers and organization managers.
    The internal items of a depot can be seen by all members of this organization.

    :author: Florian Stamer
    """

    def get(self, request, depot_id):
        depot = get_depot_if_allowed(depot_id, request.user)
        item_list = depot.visible_items(request.user)

        return render(request, 'depot/detail.html', {
            'depot': depot,
            'item_list': item_list,
            'show_visibility': depot.show_internal_items(request.user),
            'managed_by_user': depot.managed_by(request.user),
            'start_date': datetime.now() + timedelta(days=1),
            'return_date': datetime.now() + timedelta(days=4)
        })

depot/views/depot_index_view.py
from django.shortcuts import render
from django.views import View
from depot.models import Organization


class DepotIndexView(View):
    """
    Show an index page of all organizations and their depots

    Only organization managers get a link to the admin interface of their
    organization so that they can change the name and add new depots.

    :author: Florian Stamer
    :author: Benedikt Seidl
    """

    def get(self, request):
        organization_depots = []

        for organization in Organization.objects.all():
            managed_by_user = organization.managed_by(request.user)
            depots = organization.active_depots.all()

            if depots:
                organization_depots.append({
                    'model': organization,
                    'managed_by_user': managed_by_user,
                    'depots': depots
                })

        return render(request, 'depot/index.html', {
            'organization_depots': organization_depots
        })

depot/views/depot_rentals_view.py
from depot.models import Depot
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.views import View
from rental.models import Rental


class DepotRentalsView(View):
    """
    Provide an overview over all rentals for one depot

    Show labels to visually differentiate the state a
    rental is in.

    :author: Florian Stamer
    """

    def get(self, request, depot_id):
        depot = get_object_or_404(Depot, pk=depot_id)

        if not depot.managed_by(request.user):
            return HttpResponseForbidden('Not a manager of this depot')

        rentals = Rental.objects.filter(
            depot_id=depot.id,
            state__in=[Rental.STATE_PENDING, Rental.STATE_APPROVED]
        )

        return render(request, 'depot/rentals.html', {
            'rentals': rentals,
            'depot': depot,
        })

depot/templates/depot/modals/availability-modal.html
{% load i18n %}

<div class="modal fade" id="availability-modal" tabindex="-1"
        role="dialog" aria-labelledby="availability-title">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="availability-title">
                    {% blocktrans trimmed with item='<span id="availability-item"></span>' %}
                        Availability <small>of {{ item }}</small>
                    {% endblocktrans %}
                </h4>
            </div>
            <div class="modal-body">
                <canvas id="availability-chart" height="200"></canvas>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    {% trans 'Close' %}
                </button>
            </div>
        </div>
    </div>
</div>

depot/templates/depot/modals/checkout-form.html
{% load i18n %}

<div class="row">
    <div class="form-group col-md-6 {% if errors.firstname %} has-error {% endif %}">
        <label for="firstname">{% trans 'First Name' %}</label>
        <div class="input-group name">
            <input type="text" class="form-control" id="firstname"
                   name="firstname" value="{% firstof data.firstname user.first_name %}" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-user"></span>
            </span>
        </div>
        {% if errors.firstname %}
            <div class="help-block">
                {% for error in errors.firstname %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="form-group col-md-6 {% if errors.firstname %} has-error {% endif %}">
        <label for="lastname">{% trans 'Last Name' %}</label>
        <div class="input-group name">
            <input type="text" class="form-control" id="lastname"
                   name="lastname" value="{% firstof data.lastname user.last_name %}" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-user"></span>
            </span>
        </div>
        {% if errors.lastname %}
            <div class="help-block">
                {% for error in errors.lastname %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>

<div class="form-group {% if errors.email %} has-error {% endif %}">
    <label for="email">{% trans 'Email address' %}</label>
    <div class="input-group">
        <input type="email" class="form-control" id="email"
                name="email" value="{% firstof data.email user.email %}" required>
        <span class="input-group-addon">@</span>
    </div>
    {% if errors.email %}
        <div class="help-block">
            {% for error in errors.email %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
</div>

<div class="form-group {% if errors.purpose %} has-error {% endif %}">
    <label for="purpose">{% trans 'Purpose' %}</label>
    <div class="input-group">
        <textarea class="form-control" id="purpose" name="purpose"
                required>{{ data.purpose }}</textarea>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-info-sign"></span>
        </span>
    </div>
    {% if errors.purpose %}
        <div class="help-block">
            {% for error in errors.purpose %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
</div>

<div class="form-group">
    <label>{% trans 'Summary' %}</label>
    <p>
        {% blocktrans trimmed %}
            You are creating a new rental from {{ start_date }} to {{ return_date }}.
        {% endblocktrans %}
    </p>
    <table class="table rental-summary">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Location' %}</th>
            <th>{% trans 'Selected' %}</th>
        </tr>
    </table>
</div>

depot/templates/depot/modals/checkout-modal.html
{% load i18n %}

<div class="modal fade" id="checkout-modal" tabindex="-1"
        role="dialog" aria-labelledby="checkout-title">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="checkout-form" method="post" action="{% url 'rental:create' %}">
                {% csrf_token %}

                <input type="hidden" name="depot_id" value="{{ depot.id }}">
                <input type="hidden" name="start_date" value="{{ start_date_formatted }}">
                <input type="hidden" name="return_date" value="{{ return_date_formatted }}">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="checkout-title">{% trans 'Checkout' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'depot/modals/checkout-form.html' %}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary pull-left">
                        {% trans 'Submit' %}
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        {% trans 'Close' %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

depot/templates/depot/modals/date-form.html
{% load i18n %}

<div class="row">
    <div class="form-group col-md-6">
        <label for="start_date">{% trans 'Start date' %}</label>
        <div class="input-group date" id="start_date_picker">
            <input type="text" class="form-control"
                    id="start_date" name="start_date"
                    value="{{ start_date.isoformat }}" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
    <div class="form-group col-md-6">
        <label for="return_date">{% trans 'Return date' %}</label>
        <div class="input-group date" id="return_date_picker">
            <input type="text" class="form-control"
                    id="return_date" name="return_date"
                    value="{{ return_date.isoformat }}" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
</div>

{% if request.resolver_match.url_name == 'create_rental' %}
    <div class="alert alert-warning">
        {% blocktrans trimmed %}
            Changing the dates will reset all selected items because the availability
            of these items may be different in the new time frame.
        {% endblocktrans %}
    </div>
{% endif %}

depot/templates/depot/modals/date-modal.html
{% load i18n %}

<div class="modal fade" id="date-modal" tabindex="-1"
        role="dialog" aria-labelledby="date-title">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="checkout-form" method="get" action="{% url 'depot:create_rental' depot.id %}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="date-title">{% trans 'Pick a time frame' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'depot/modals/date-form.html' %}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary pull-left">
                        {% trans 'Select' %}
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        {% trans 'Close' %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>